### ISSUE TITLE
Возникает ошибка при компиляции в Xcode 12.5 (12E262)

### ISSUE THREAD

**Issue by fs-vladimir** [uxfb/uxfeedback-sdk-ios#1]
При попытке собрать проект в последней версии Xcode возникает ошибка.

UXFeedbackSDK/UXFeedbackSDK.framework/Modules/UXFeedbackSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:252:1: Conformance of 'Reachability.NetworkStatus' to 'Equatable' is unavailable

Failed to build module 'UXFeedbackSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'

**Comment by potemka** [comment]
@fs-vladimir обновил версию, попробуйте 1.0.7

**Comment by fs-vladimir** [comment]
@potemka работает, спасибо.
